# 1

jobs:
  include:
    - stage: test
      language: node_js
      node_js: 10.15.3
      cache: npm
      install: 
       - cd packages/rnv
       - npm i > /dev/null 2>&1
       - npm run fix
       - npm link
      script: npm run setup
    - language: android
      sudo: required
      jdk: oraclejdk8
      cache: npm
      android:
        components:
          - tools-26.1.1
          - build-tools-28.0.3
          - emulator
          - extra-google-m2repository
          - extra-android-m2repository
          - patcher-v4
          - platform-tools
          - android-28
          - sys-img-x86-android-28
      before_install:
        - curl -sL https://deb.nodesource.com/setup_8.x | sudo -E bash -
        - sudo apt-get install -y nodejs
      script: 
        - cd packages/rnv
        - npm i
        - ls node_modules/react-native
        - npm run test
      
      

stages:
  - test
