env:
  global:
    - NODE_OPTIONS=--max_old_space_size=8192
    - ACCOUNT_NAME=rnv
    - REPO_NAME=pavjacko/renative
    - PROJECT_NAME=renative
jobs:
  include:
    - name: "HelloWorld iOS: E2E"
      language: node_js
      cache:
        directories:
          - node_modules
      node_js: 13.13.0
      os: osx
      osx_image: xcode11.3
      install: skip
      script: ci/run_osx.sh
    - name: "RNV iOS: Integration"
      language: node_js
      cache:
        directories:
          - node_modules
      node_js: 13.13.0
      os: osx
      osx_image: xcode11.3
      install:
        - yarn bootstrap
        - cd packages/rnv
      script: yarn test:ios
    - name: "HelloWorld Android: E2E"
      language: android
      cache:
        directories:
          - node_modules
          - $HOME/.gradle
      sudo: required
      jdk: oraclejdk8
      android:
        components:
          - tools
          - build-tools-28.0.3
          - extra-google-m2repository
          - extra-android-m2repository
          - platform-tools
          - android-28
          - sys-img-x86-android-28
      install:
        - nvm install 13.13.0
        - echo yes | sdkmanager "platforms;android-28"
        - rm -rf ~/.yarn/bin/yarn || true && npm uninstall --global yarn; npm install --global yarn; yarn --version
        - yarn bootstrap
      script: ci/run_linux.sh
    - name: "HelloWorld Web: E2E"
      dist: trusty
      language: node_js
      cache:
        directories:
          - node_modules
      node_js: 13.13.0
      install:
        - rm -rf ~/.yarn/bin/yarn || true && npm uninstall --global yarn; npm install --global yarn; yarn --version
        - yarn bootstrap
        - cd packages/app
      script: yarn e2e-web
    - name: "RNV Android: Integration"
      language: android
      dist: trusty
      cache:
        directories:
          - node_modules
          - $HOME/.gradle
      sudo: required
      jdk: oraclejdk8
      android:
        components:
          - tools-26.1.1
          - build-tools-28.0.3
          - extra-google-m2repository
          - extra-android-m2repository
          - platform-tools-28.0.2
          - android-28
          - sys-img-x86-android-28
      install:
        - nvm install 13.13.0
        - echo yes | sdkmanager "platforms;android-28"
        - rm -rf ~/.yarn/bin/yarn || true && npm uninstall --global yarn; npm install --global yarn; yarn --version
        - yarn bootstrap
        - cd packages/rnv
      script: yarn test:integration
    - name: "RNV Node: Unit Tests"
      dist: trusty
      language: node_js
      cache:
        directories:
          - node_modules
      node_js: 13.13.0
      install:
        - rm -rf ~/.yarn/bin/yarn || true && npm uninstall --global yarn; npm install --global yarn; yarn --version
        - yarn bootstrap
        - cd packages/rnv
      script: npm run test:setup
