# 1

jobs:
  include:
    - stage: test
      language: node_js
      node_js: 10.15.3
      cache: npm
      install: 
       - npm run fix
       - npm i > /dev/null 2>&1
       - cd packages/rnv
       - npm i > /dev/null 2>&1
       - npm run fix
       - npm link
      script: npm run test

stages:
  - test
